- name: Configurar servidor de banco de dados
  hosts: db-01
  user: "Charles"
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db-01"
    - dbusername: "Charles"
    - dbpassword: "charles123#"
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{ item }}"
      with_items:
        - 192.168.1.2 control-node
        - 192.168.1.3 app-01
        - 192.168.1.4 db-01

  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
