mysql_root_password: vagrant
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp-01
    host: "%"
    password: vagrant
    priv: "notes.*:ALL"