
Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
  config.vm.hostname = "app-01"
  config.vm.network "private_network", ip: "192.168.1.3"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "provision.sh"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }

end